config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'home/index'
  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resources :comments, only: [:create]
  end

  root to: "home#index"

  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, length: { maximum: 140 }
	validates :text, length: { maximum: 400 }
	validates :text, presence: true
	validates :title, presence: true
	has_many :comments
	def subject
		title
	end
	def last_comment
		comments.last
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, length: { maximum: 400 }
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :email, presence: true
	validates :message, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller? # if для того, чтобы before выполнялся только для devise_controller, для других контроллеров выполнятся не будет

	private
	def configure_permitted_parameters
	   devise_parameter_sanitizer.for(:sign_up) << :username
	   devise_parameter_sanitizer.for(:sign_in) << :username
	   devise_parameter_sanitizer.for(:account_update) << :username
	end 

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :authenticate_user!, except: [:index]	
	

	def index

		@articles = Article.all
		@user = current_user
		
	end


	def show

		@article = Article.find(params[:id])

	end

	def new
		
	end
	
	def create
		@article = Article.new (article_params)
		@article[:username] = current_user.username
		if @article.save
			redirect_to @article
		else
			render action: 'new'
		end	
	end

	def edit

		@article = Article.find(params[:id])

	end

	def update

		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render action: 'edit'
		end	
	end

	def destroy
		article = Article.find(params[:id])
		@ident = params[:id]
		article.destroy
		# render action: 'index'
	end

private   
# разрешение передачи данных со страницы браузера на сервер

	def article_params
		params.require(:article).permit(:title, :text)
	end		

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_filter :authenticate_user!, :only => [:create]	
	def create
		@article = Article.find(params[:article_id])
		
		@article.comments.create(:body => comment_params[:body], :author => current_user.username)
		redirect_to article_path(@article)
	end

private   
# разрешение передачи данных со страницы браузера на сервер

	def comment_params
		params.require(:comment).permit(:body)
	end		


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new (contact_params)
		if @contact.valid?
			@contact.save
		else
			render action: 'new'
		end

	end

	private   
# разрешение передачи данных со страницы браузера на сервер

	def contact_params
		params.require(:contact).permit(:email, :message)
	end		
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@articles = Article.all
  	redirect_to articles_path
  	#render 'articles/index'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def terms
	end

	def about
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/create.html.erb
<h1> <%= t('articles.thank_you') %> </h1>
<p><%= t('articles.created') %></p>

<a href="/articles"><%= t('articles.show_all') %></a> <br />

<%= link_to t('articles.show_all'), articles_path   %>

app/views/articles/destroy.html.erb
<h1> <%= t('articles.art_destroy', par: @ident) %> </h1>

<%= link_to t('articles.show_all'), articles_path   %>

app/views/articles/edit.html.erb
<h1><%= t('articles.edit_h1') %></h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %> <!-- Вместо '/articles' можно ввести переменную articles_path -->
	<p>
		<%= f.label t('articles.title') %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label t('articles.text')%><br />
		<%= f.text_area :text %>
	</p>
	<p>
		<%= f.submit t('articles.edit_button') %><br />
	
	</p>
<%end%>
<%= form_for :article, url: article_path(@article), method: :delete do |f| %>

	<!-- <p>
		<%= f.submit 'Delete article' %><br />
	
	</p> -->


<%end%>

app/views/articles/index.html.erb
<h1> <%= t('articles.list_of') %> </h1>

<% @articles.each do |article| %>

<h2> 

	<%= article.title %>

</h2>

<p>

	<%= article.text %>

</p>

<p>

	<%= link_to t('articles.show') , article_path(article) %> 
	<% if @user && @user.username == article.username %>
	| <%= link_to t('articles.edit'), edit_article_path(article) %> |
	<%= link_to t('articles.destroy'), article_path(article), method: :delete %>
	<% end %>
</p>

<hr />

<% end %>

app/views/articles/new.html.erb
<h1><%= t('articles.new_h1') %></h1>

<%= form_for :article, url: articles_path do |f| %> <!-- Вместо '/articles' можно ввести переменную articles_path -->
	<p>
		<%= f.label t('articles.title') %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label t('articles.text')%><br />
		<%= f.text_area :text %>
	</p>
	<p>
		
		<%= f.submit t('articles.save') %><br />
	
	</p>
<%end%>

app/views/articles/show.html.erb
<h1> <%= @article.title %> </h1>

<p>

	<%= @article.text %>

</p>

<p>
	<a href="/articles"><%= t('articles.show_all') %></a> |
	<%= link_to t('articles.show_all'), articles_path   %>
</p>

<% @article.comments.each do |comment| %>

<p> 

	<i> <%= t('articles.author_said', par: comment.author) %></i><br />
	<%= comment.body %> <br />

	

</p>
<% end %>
<p>
	<%= form_for([@article, @article.comments.build])  do |f| %> 
		
		<!-- <p>
			<%= f.label :author %><br />
			<%= f.text_field :author %>
		</p> -->
		<p>
			<%= f.label t('articles.comment_body') %><br />
			<%= f.text_area :body %>
		</p>
		<p>
			<%= f.submit t('articles.comment_button') %><br />
		</p>

	<%end%>

</p>

app/views/contacts/create.html.erb
<h1>Thanks</h1>

app/views/contacts/new.html.erb
<h1><%= t('contacts.contact_us') %></h1>

<%= form_for :contact, url: contacts_path do |f| %> <!-- Вместо '/articles' можно ввести переменную articles_path -->
	<p>
		<ul>

		<%  @contact.errors.full_messages.each do |msg|  %>
			<li> <%= msg %> </li>

		<% end %>
		</ul>

	</p>

	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :message %><br />
		<%= f.text_area :message %>
	</p>
	<p>
		<%= f.submit 'Send message' %><br />
	
	</p>
<%end%>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <script data-require="jquery@*" data-semver="2.1.4" src="https://code.jquery.com/jquery-2.1.4.js"></script>
   <script data-require="bootstrap@*" data-semver="3.3.6" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
   <link data-require="bootstrap-css@3.3.6" data-semver="3.3.6" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" />
</head>
<body>
	<div class="container">
		<nav class="navbar navbar-default">	
			<div class="container-fluid">	
				<a class="navbar-brand" href="/articles">Blog</a> 
				<ul class="nav navbar-nav">
        			<li class="active"><a href="/articles/new">New article <span class="sr-only">(current)</span></a></li>
              	</ul>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
					<li><p class="navbar-text">Hello, <%= current_user.username %></p></li>
					<li><%= link_to 'Sign Out!', destroy_user_session_path, method: :delete %> </li>  <!-- <a href="/users/sign_out" data-method = delete>Sign out</a> -->
					<% else %>
					<li><%= link_to 'Sign In!', new_user_session_path %> </li>  <!-- Можно дать такую ссылку - <a href="/users/sign_in">Sign In</a>, параметр new_user_session_path(Helper for Devise) взят из списка маршрутов -->
					<li><%= link_to 'Sign Up!', new_user_registration_path %> </li>  <!-- <a href="/users/sign_up">Sign Up</a> --> 
					<% end %>
				</ul>
			</div>
		</nav>

		
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1> About </h1>

app/views/pages/terms.html.erb
<h1> Terms page</h1>